### ISSUE TITLE
How to activate with Alexa?

### ISSUE THREAD

**Issue by reillychase** [masters1222/mm-hide-all#4]
If anyone wants to work together to get this module working by Alexa command, let me know. Would be interested

**Comment by fabrang** [comment]
Sounds nice I want to do it aswell, but with Google VC.  Did you allready make a Progress or got some Tips ? As an alternative I was thinking about a VC that only turns HDMI supply on or off

**Comment by AlexDespain01** [comment]
Will not be supported
